import fs from 'fs';

function save(path, varName, data) {
  const content = `import { CursorProject } from '../../types/cursor';\n\nexport const ${varName}: CursorProject[] = ${JSON.stringify(data, null, 2)};\n`;
  fs.writeFileSync(path, content, 'utf8');
  console.log(`Saved ${path}`);
}

function saveSpecial(path, varName, data) {
  const content = `import { CursorProject } from '../types/cursor';\n\nexport const ${varName}: CursorProject[] = ${JSON.stringify(data, null, 2)};\n`;
  fs.writeFileSync(path, content, 'utf8');
  console.log(`Saved ${path}`);
}

// 5. CYBER CURSORS
const CYBER_DATA = [
  {
    id: 'cyber-neon-katana',
    title: 'Cyberpunk Neon Katana & Glitch Blade',
    slug: 'cyberpunk-neon-katana-glitch-blade',
    category: 'Cyber Sci-Fi',
    description: 'Ultraviolet laser katana blade with radioactive neon cyan hologram trail.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 4 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['cyberpunk', 'katana', 'neon', 'laser', 'scifi'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'NeoTokyo2099',
    isFeatured: true,
    isAnimated: true,
    animationType: 'pulse',
    downloadsCount: 81200,
    likesCount: 36400,
    layers: [
      {
        id: 'cy-katana',
        name: 'Laser Katana',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: -45,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🗡️', size: 26 },
        glow: { enabled: true, color: '#ec4899', blur: 6 },
      },
      {
        id: 'cy-spark',
        name: 'Plasma Bolt',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⚡', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'cy-ptr-chip',
        name: 'Neural Core',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💾', size: 24 },
        glow: { enabled: true, color: '#06b6d4', blur: 8 },
      },
      {
        id: 'cy-ptr-spark',
        name: 'Cyber Dust',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 13 },
      },
    ],
  },
  {
    id: 'cyber-matrix-code',
    title: 'Matrix Terminal & Green Rain Stream',
    slug: 'matrix-digital-rain-terminal',
    category: 'Cyber Sci-Fi',
    description: 'Cascading phosphor green Matrix digital rain glyphs with cyberpunk console terminal.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['matrix', 'code', 'terminal', 'hacker', 'scifi'],
    createdAt: '2026-08-19T10:00:00.000Z',
    updatedAt: '2026-08-19T10:00:00.000Z',
    author: 'NeoOperator',
    isFeatured: true,
    isAnimated: true,
    animationType: 'pulse',
    downloadsCount: 75400,
    likesCount: 32800,
    layers: [
      {
        id: 'mx-code',
        name: 'Terminal Screen',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '📟', size: 26 },
        glow: { enabled: true, color: '#22c55e', blur: 6 },
      },
      {
        id: 'mx-bin',
        name: 'Binary Rain',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🟢', size: 13 },
      },
    ],
    pointerLayers: [
      {
        id: 'mx-ptr-key',
        name: 'Access Key',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔑', size: 24 },
        glow: { enabled: true, color: '#16a34a', blur: 8 },
      },
      {
        id: 'mx-ptr-spark',
        name: 'Code Sparkle',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 13 },
      },
    ],
  },
  {
    id: 'cyber-plasma-blaster',
    title: 'Plasma Rifle & Energy Cannon Blast',
    slug: 'plasma-rifle-energy-cannon-blast',
    category: 'Cyber Sci-Fi',
    description: 'High-tech sci-fi plasma rifle blasting electric blue ionized charge particles.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 4 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['plasma', 'blaster', 'rifle', 'laser', 'scifi'],
    createdAt: '2026-08-18T10:00:00.000Z',
    updatedAt: '2026-08-18T10:00:00.000Z',
    author: 'QuantumArmory',
    isFeatured: true,
    isAnimated: true,
    animationType: 'sparkle',
    downloadsCount: 68900,
    likesCount: 28400,
    layers: [
      {
        id: 'pl-gun',
        name: 'Plasma Gun',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: -20,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔫', size: 26 },
        glow: { enabled: true, color: '#38bdf8', blur: 6 },
      },
      {
        id: 'pl-spark',
        name: 'Ion Spark',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⚡', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'pl-ptr-blast',
        name: 'Plasma Orb',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔵', size: 24 },
        glow: { enabled: true, color: '#0284c7', blur: 8 },
      },
      {
        id: 'pl-ptr-pow',
        name: 'Energy Impact',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💥', size: 13 },
      },
    ],
  },
  {
    id: 'cyber-mecha-gundam',
    title: 'Mecha Gundam Helm & Beam Saber',
    slug: 'mecha-gundam-helm-beam-saber',
    category: 'Cyber Sci-Fi',
    description: 'Armored Mecha robotic battle helmet with pink thermal beam saber melee blade.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['mecha', 'gundam', 'robot', 'saber', 'scifi'],
    createdAt: '2026-08-17T10:00:00.000Z',
    updatedAt: '2026-08-17T10:00:00.000Z',
    author: 'MechaHangar',
    isFeatured: true,
    isAnimated: true,
    animationType: 'wiggle',
    downloadsCount: 64200,
    likesCount: 26700,
    layers: [
      {
        id: 'mc-helm',
        name: 'Robot Helmet',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🤖', size: 26 },
        glow: { enabled: true, color: '#ef4444', blur: 6 },
      },
      {
        id: 'mc-saber',
        name: 'Beam Saber',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: -30,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🪄', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'mc-ptr-shield',
        name: 'Energy Barrier',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🛡️', size: 24 },
        glow: { enabled: true, color: '#dc2626', blur: 8 },
      },
      {
        id: 'mc-ptr-spark',
        name: 'Thruster Fire',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔥', size: 13 },
      },
    ],
  },
  {
    id: 'cyber-neural-chip',
    title: 'Quantum Neural Processor & Circuit Trace',
    slug: 'quantum-neural-processor-circuit-trace',
    category: 'Cyber Sci-Fi',
    description: 'Gold-plated cybernetic quantum microchip with glowing cyan PCB circuit conduits.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['chip', 'processor', 'circuit', 'quantum', 'scifi'],
    createdAt: '2026-08-16T10:00:00.000Z',
    updatedAt: '2026-08-16T10:00:00.000Z',
    author: 'CyberLabX',
    isFeatured: true,
    isAnimated: true,
    animationType: 'sparkle',
    downloadsCount: 59300,
    likesCount: 24500,
    layers: [
      {
        id: 'nc-chip',
        name: 'Quantum CPU',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💽', size: 26 },
        glow: { enabled: true, color: '#06b6d4', blur: 6 },
      },
      {
        id: 'nc-spark',
        name: 'Data Pulse',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'nc-ptr-hub',
        name: 'Data Crystal',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💎', size: 24 },
        glow: { enabled: true, color: '#0891b2', blur: 8 },
      },
      {
        id: 'nc-ptr-bit',
        name: 'Byte Particle',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⚡', size: 13 },
      },
    ],
  },
  {
    id: 'cyber-vr-visor',
    title: 'HoloLens VR Visor & Metaverse Eye',
    slug: 'hololens-vr-visor-metaverse-eye',
    category: 'Cyber Sci-Fi',
    description: 'Futuristic augmented reality HUD glasses with holographic wireframe prism pointer.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['vr', 'ar', 'visor', 'metaverse', 'scifi'],
    createdAt: '2026-08-15T10:00:00.000Z',
    updatedAt: '2026-08-15T10:00:00.000Z',
    author: 'MetaVisor',
    isFeatured: true,
    isAnimated: true,
    animationType: 'pulse',
    downloadsCount: 56100,
    likesCount: 22800,
    layers: [
      {
        id: 'vr-goggles',
        name: 'VR Visor',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🥽', size: 26 },
        glow: { enabled: true, color: '#a855f7', blur: 6 },
      },
      {
        id: 'vr-holo',
        name: 'Holo Spark',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔮', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'vr-ptr-cube',
        name: 'Wireframe Cube',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🧊', size: 24 },
        glow: { enabled: true, color: '#9333ea', blur: 8 },
      },
      {
        id: 'vr-ptr-spark',
        name: 'Grid Sparkle',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 13 },
      },
    ],
  },
  {
    id: 'cyber-arcade-synthwave',
    title: 'Outrun Synthwave Sun & Palm Grid',
    slug: 'outrun-synthwave-sun-palm-grid',
    category: 'Cyber Sci-Fi',
    description: 'Neon magenta retrowave setting sun over wireframe highway horizon with retro cassette.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['synthwave', 'outrun', 'neon', 'retro', '80s'],
    createdAt: '2026-08-14T10:00:00.000Z',
    updatedAt: '2026-08-14T10:00:00.000Z',
    author: 'KavinskyVibe',
    isFeatured: true,
    isAnimated: true,
    animationType: 'rainbow',
    downloadsCount: 78900,
    likesCount: 35200,
    layers: [
      {
        id: 'sw-sun',
        name: 'Sunset Sun',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🌅', size: 26 },
        glow: { enabled: true, color: '#ec4899', blur: 6 },
      },
      {
        id: 'sw-palm',
        name: 'Palm Tree',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🌴', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'sw-ptr-tape',
        name: 'Cassette Tape',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '📼', size: 24 },
        glow: { enabled: true, color: '#f43f5e', blur: 8 },
      },
      {
        id: 'sw-ptr-star',
        name: 'Neon Star',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⭐', size: 13 },
      },
    ],
  },
  {
    id: 'cyber-dark-matter',
    title: 'Dark Matter Singularity & Black Hole',
    slug: 'dark-matter-singularity-black-hole',
    category: 'Cyber Sci-Fi',
    description: 'Cosmic gravitational vortex black hole warping spacetime with accretion disc glow.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 4 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['blackhole', 'space', 'galaxy', 'darkmatter', 'scifi'],
    createdAt: '2026-08-13T10:00:00.000Z',
    updatedAt: '2026-08-13T10:00:00.000Z',
    author: 'AstrophysicsLab',
    isFeatured: true,
    isAnimated: true,
    animationType: 'spin',
    downloadsCount: 87100,
    likesCount: 39600,
    layers: [
      {
        id: 'dm-hole',
        name: 'Singularity Hole',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🕳️', size: 26 },
        glow: { enabled: true, color: '#8b5cf6', blur: 6 },
      },
      {
        id: 'dm-swirl',
        name: 'Vortex Swirl',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🌀', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'dm-ptr-ring',
        name: 'Saturn Ring',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🪐', size: 24 },
        glow: { enabled: true, color: '#7c3aed', blur: 8 },
      },
      {
        id: 'dm-ptr-spark',
        name: 'Stardust',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 13 },
      },
    ],
  },
  {
    id: 'cyber-drone-recon',
    title: 'Recon Drone Quadcopter & Surveillance HUD',
    slug: 'recon-drone-quadcopter-surveillance-hud',
    category: 'Cyber Sci-Fi',
    description: 'High altitude stealth drone with rotating propellers and target tracking optical beacon.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['drone', 'recon', 'stealth', 'camera', 'scifi'],
    createdAt: '2026-08-12T10:00:00.000Z',
    updatedAt: '2026-08-12T10:00:00.000Z',
    author: 'SkynetOps',
    isFeatured: true,
    isAnimated: true,
    animationType: 'wiggle',
    downloadsCount: 51800,
    likesCount: 21400,
    layers: [
      {
        id: 'dr-quad',
        name: 'Quadcopter',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🛸', size: 26 },
        glow: { enabled: true, color: '#14b8a6', blur: 6 },
      },
      {
        id: 'dr-cam',
        name: 'Sensor Eye',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '📹', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'dr-ptr-sat',
        name: 'Orbital Dish',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '📡', size: 24 },
        glow: { enabled: true, color: '#0d9488', blur: 8 },
      },
      {
        id: 'dr-ptr-dot',
        name: 'Laser Ping',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔴', size: 13 },
      },
    ],
  },
  {
    id: 'cyber-biohazard-nanite',
    title: 'Nanite Swarm & Cyber Tox Needle',
    slug: 'nanite-swarm-cyber-tox-needle',
    category: 'Cyber Sci-Fi',
    description: 'Microscopic medical nanobots carrying glowing toxic green restorative compound.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 4 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['nanite', 'biohazard', 'syringe', 'toxin', 'scifi'],
    createdAt: '2026-08-11T10:00:00.000Z',
    updatedAt: '2026-08-11T10:00:00.000Z',
    author: 'BioTechCyber',
    isFeatured: true,
    isAnimated: true,
    animationType: 'sparkle',
    downloadsCount: 48900,
    likesCount: 19800,
    layers: [
      {
        id: 'bh-needle',
        name: 'Injector Syringe',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: -45,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💉', size: 26 },
        glow: { enabled: true, color: '#84cc16', blur: 6 },
      },
      {
        id: 'bh-tox',
        name: 'Nanite Germ',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🦠', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'bh-ptr-rad',
        name: 'Radioactive Pill',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💊', size: 24 },
        glow: { enabled: true, color: '#65a30d', blur: 8 },
      },
      {
        id: 'bh-ptr-drop',
        name: 'Green Liquid',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🧪', size: 13 },
      },
    ],
  },
];

save('src/data/categories/cyberCursors.ts', 'CYBER_CURSORS', CYBER_DATA);
