import fs from 'fs';

function save(path, varName, data) {
  const content = `import { CursorProject } from '../../types/cursor';\n\nexport const ${varName}: CursorProject[] = ${JSON.stringify(data, null, 2)};\n`;
  fs.writeFileSync(path, content, 'utf8');
  console.log(`Saved ${path}`);
}

function saveSpecial(path, varName, data) {
  const content = `import { CursorProject } from '../types/cursor';\n\nexport const ${varName}: CursorProject[] = ${JSON.stringify(data, null, 2)};\n`;
  fs.writeFileSync(path, content, 'utf8');
  console.log(`Saved ${path}`);
}

// 7. TECH & OS CURSORS
const TECH_DATA = [
  {
    id: 'tech-macos-beachball',
    title: 'macOS Rainbow Spinning Beachball & Command Key',
    slug: 'macos-rainbow-spinning-beachball-command',
    category: 'Tech & OS',
    description: 'Iconic spinning rainbow pinwheel wait cursor with classic Apple Command key symbol.',
    cursorType: 'normal',
    hotspot: { x: 12, y: 12 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['macos', 'apple', 'beachball', 'rainbow', 'os'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'CupertinoDev',
    isFeatured: true,
    isAnimated: true,
    animationType: 'spin',
    downloadsCount: 88400,
    likesCount: 37900,
    layers: [
      {
        id: 'mc-ball',
        name: 'Spinning Ball',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔮', size: 26 },
        glow: { enabled: true, color: '#38bdf8', blur: 6 },
      },
      {
        id: 'mc-spark',
        name: 'Rainbow Sparkle',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'mc-ptr-apple',
        name: 'Apple Icon',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🍏', size: 24 },
        glow: { enabled: true, color: '#22c55e', blur: 8 },
      },
      {
        id: 'mc-ptr-gear',
        name: 'System Gear',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⚙️', size: 13 },
      },
    ],
  },
  {
    id: 'tech-windows-bsod',
    title: 'Windows Blue Screen & Sad Face',
    slug: 'windows-blue-screen-sad-face',
    category: 'Tech & OS',
    description: 'Classic Windows blue screen error crash with white frowning emoticon and QR code.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['windows', 'bsod', 'error', 'microsoft', 'os'],
    createdAt: '2026-08-19T10:00:00.000Z',
    updatedAt: '2026-08-19T10:00:00.000Z',
    author: 'RedmondCrash',
    isFeatured: true,
    isAnimated: true,
    animationType: 'pulse',
    downloadsCount: 79200,
    likesCount: 34100,
    layers: [
      {
        id: 'wd-comp',
        name: 'Blue Screen Monitor',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🖥️', size: 26 },
        glow: { enabled: true, color: '#3b82f6', blur: 6 },
      },
      {
        id: 'wd-sad',
        name: 'Sad Face',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '☹️', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'wd-ptr-warn',
        name: 'Warning Triangle',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⚠️', size: 24 },
        glow: { enabled: true, color: '#eab308', blur: 8 },
      },
      {
        id: 'wd-ptr-bomb',
        name: 'Crash Bomb',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💣', size: 13 },
      },
    ],
  },
  {
    id: 'tech-linux-tux',
    title: 'Linux Tux Penguin & Root Terminal',
    slug: 'linux-tux-penguin-root-terminal',
    category: 'Tech & OS',
    description: 'Friendly Linux kernel mascot Tux penguin holding Bash sudo terminal shell prompt.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['linux', 'tux', 'ubuntu', 'terminal', 'opensource'],
    createdAt: '2026-08-18T10:00:00.000Z',
    updatedAt: '2026-08-18T10:00:00.000Z',
    author: 'KernelHacker',
    isFeatured: true,
    isAnimated: true,
    animationType: 'wiggle',
    downloadsCount: 84600,
    likesCount: 36800,
    layers: [
      {
        id: 'lx-tux',
        name: 'Tux Penguin',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🐧', size: 26 },
        glow: { enabled: true, color: '#f59e0b', blur: 6 },
      },
      {
        id: 'lx-fish',
        name: 'Little Fish',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🐟', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'lx-ptr-term',
        name: 'Prompt Terminal',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💻', size: 24 },
        glow: { enabled: true, color: '#22c55e', blur: 8 },
      },
      {
        id: 'lx-ptr-prompt',
        name: 'Bash Shell',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⌨️', size: 13 },
      },
    ],
  },
  {
    id: 'tech-github-octocat',
    title: 'GitHub Octocat & Merge Pull Request',
    slug: 'github-octocat-merge-pull-request',
    category: 'Tech & OS',
    description: 'Beloved GitHub Octocat mascot silhouette with purple merged Git commit branch node.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['github', 'octocat', 'git', 'coding', 'developer'],
    createdAt: '2026-08-17T10:00:00.000Z',
    updatedAt: '2026-08-17T10:00:00.000Z',
    author: 'GitCommitMaster',
    isFeatured: true,
    isAnimated: true,
    animationType: 'sparkle',
    downloadsCount: 91200,
    likesCount: 41500,
    layers: [
      {
        id: 'gh-cat',
        name: 'Octocat Face',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🐙', size: 26 },
        glow: { enabled: true, color: '#a855f7', blur: 6 },
      },
      {
        id: 'gh-star',
        name: 'Repo Star',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⭐', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'gh-ptr-branch',
        name: 'Git Merge',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🌿', size: 24 },
        glow: { enabled: true, color: '#8b5cf6', blur: 8 },
      },
      {
        id: 'gh-ptr-check',
        name: 'Green Check',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✅', size: 13 },
      },
    ],
  },
  {
    id: 'tech-vscode-syntax',
    title: 'VS Code Blue Ribbon & TypeScript Logo',
    slug: 'vs-code-blue-ribbon-typescript-logo',
    category: 'Tech & OS',
    description: 'Crisp blue Microsoft Visual Studio Code folded infinity ribbon with TypeScript TS shield.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['vscode', 'typescript', 'ide', 'code', 'microsoft'],
    createdAt: '2026-08-16T10:00:00.000Z',
    updatedAt: '2026-08-16T10:00:00.000Z',
    author: 'CodeWizard',
    isFeatured: true,
    isAnimated: true,
    animationType: 'pulse',
    downloadsCount: 76800,
    likesCount: 33700,
    layers: [
      {
        id: 'vs-icon',
        name: 'VS Code Infinity',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔷', size: 26 },
        glow: { enabled: true, color: '#0284c7', blur: 6 },
      },
      {
        id: 'vs-spark',
        name: 'Syntax Spark',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⚡', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'vs-ptr-gear',
        name: 'IDE Settings',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⚙️', size: 24 },
        glow: { enabled: true, color: '#38bdf8', blur: 8 },
      },
      {
        id: 'vs-ptr-bug',
        name: 'Debugger Bug',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🐛', size: 13 },
      },
    ],
  },
  {
    id: 'tech-react-atom',
    title: 'React Atomic Orbit & State Hook',
    slug: 'react-atomic-orbit-state-hook',
    category: 'Tech & OS',
    description: 'Electric cyan rotating React.js atomic particle nucleus with useState hook symbol.',
    cursorType: 'normal',
    hotspot: { x: 12, y: 12 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['react', 'javascript', 'frontend', 'atom', 'developer'],
    createdAt: '2026-08-15T10:00:00.000Z',
    updatedAt: '2026-08-15T10:00:00.000Z',
    author: 'ReactNinja',
    isFeatured: true,
    isAnimated: true,
    animationType: 'spin',
    downloadsCount: 89300,
    likesCount: 39700,
    layers: [
      {
        id: 'rc-atom',
        name: 'React Atom',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⚛️', size: 26 },
        glow: { enabled: true, color: '#06b6d4', blur: 6 },
      },
      {
        id: 'rc-sparkle',
        name: 'Cyan Spark',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'rc-ptr-bolt',
        name: 'Component Bolt',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⚡', size: 24 },
        glow: { enabled: true, color: '#0891b2', blur: 8 },
      },
      {
        id: 'rc-ptr-heart',
        name: 'Love React',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💙', size: 13 },
      },
    ],
  },
  {
    id: 'tech-docker-whale',
    title: 'Docker Whale Container & Ship Anchor',
    slug: 'docker-whale-container-ship-anchor',
    category: 'Tech & OS',
    description: 'Friendly ocean blue Docker whale carrying cargo containers across containerized seas.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['docker', 'devops', 'whale', 'containers', 'cloud'],
    createdAt: '2026-08-14T10:00:00.000Z',
    updatedAt: '2026-08-14T10:00:00.000Z',
    author: 'DevOpsCaptain',
    isFeatured: true,
    isAnimated: true,
    animationType: 'wiggle',
    downloadsCount: 65400,
    likesCount: 28900,
    layers: [
      {
        id: 'dk-whale',
        name: 'Docker Whale',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🐳', size: 26 },
        glow: { enabled: true, color: '#0284c7', blur: 6 },
      },
      {
        id: 'dk-box',
        name: 'Cargo Box',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '📦', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'dk-ptr-ship',
        name: 'Cargo Ship',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🚢', size: 24 },
        glow: { enabled: true, color: '#0369a1', blur: 8 },
      },
      {
        id: 'dk-ptr-anchor',
        name: 'Anchor',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⚓', size: 13 },
      },
    ],
  },
  {
    id: 'tech-cyber-keyboard',
    title: 'Mechanical Keycap Click & Rainbow RGB Switch',
    slug: 'mechanical-keycap-click-rainbow-rgb',
    category: 'Tech & OS',
    description: 'Custom mechanical keyboard switch keycap with reactive click ripple RGB aura.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['keyboard', 'rgb', 'mechanical', 'custom', 'hardware'],
    createdAt: '2026-08-13T10:00:00.000Z',
    updatedAt: '2026-08-13T10:00:00.000Z',
    author: 'KeebBuilder',
    isFeatured: true,
    isAnimated: true,
    animationType: 'rainbow',
    downloadsCount: 73200,
    likesCount: 31600,
    layers: [
      {
        id: 'kb-key',
        name: 'Keycap',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⌨️', size: 26 },
        glow: { enabled: true, color: '#ec4899', blur: 6 },
      },
      {
        id: 'kb-sparkle',
        name: 'RGB Sparkle',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'kb-ptr-mouse',
        name: 'Gaming Mouse',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🖱️', size: 24 },
        glow: { enabled: true, color: '#f43f5e', blur: 8 },
      },
      {
        id: 'kb-ptr-fire',
        name: 'RGB Fire',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔥', size: 13 },
      },
    ],
  },
  {
    id: 'tech-retro-floppy',
    title: 'Retro 3.5 Floppy Disk & 90s CRT Monitor',
    slug: 'retro-3-5-floppy-disk-crt-monitor',
    category: 'Tech & OS',
    description: 'Nostalgic 1.44MB black 3.5 inch floppy diskette with classic glowing 90s CRT PC.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['floppy', 'retro', '90s', 'vintage', 'hardware'],
    createdAt: '2026-08-12T10:00:00.000Z',
    updatedAt: '2026-08-12T10:00:00.000Z',
    author: 'VaporNostalgia',
    isFeatured: true,
    isAnimated: true,
    animationType: 'wiggle',
    downloadsCount: 61900,
    likesCount: 26400,
    layers: [
      {
        id: 'fp-disk',
        name: 'Floppy Disk',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💾', size: 26 },
        glow: { enabled: true, color: '#38bdf8', blur: 6 },
      },
      {
        id: 'fp-save',
        name: 'Save Check',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💾', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'fp-ptr-crt',
        name: 'CRT Monitor',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🖥️', size: 24 },
        glow: { enabled: true, color: '#0ea5e9', blur: 8 },
      },
      {
        id: 'fp-ptr-cd',
        name: 'Compact Disc',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💿', size: 13 },
      },
    ],
  },
  {
    id: 'tech-ai-gemini-spark',
    title: 'Gemini AI Spark & Quantum Intelligence',
    slug: 'gemini-ai-spark-quantum-intelligence',
    category: 'Tech & OS',
    description: 'Radiant four-pointed Gemini AI gradient star pulsing with intelligent neural data beams.',
    cursorType: 'normal',
    hotspot: { x: 12, y: 12 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['ai', 'gemini', 'google', 'neural', 'future'],
    createdAt: '2026-08-11T10:00:00.000Z',
    updatedAt: '2026-08-11T10:00:00.000Z',
    author: 'DeepMindPioneer',
    isFeatured: true,
    isAnimated: true,
    animationType: 'sparkle',
    downloadsCount: 98100,
    likesCount: 47200,
    layers: [
      {
        id: 'gm-spark',
        name: 'Gemini Star',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 26 },
        glow: { enabled: true, color: '#38bdf8', blur: 6 },
      },
      {
        id: 'gm-bulb',
        name: 'Idea Spark',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💡', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'gm-ptr-brain',
        name: 'Neural Brain',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🧠', size: 24 },
        glow: { enabled: true, color: '#6366f1', blur: 8 },
      },
      {
        id: 'gm-ptr-star',
        name: 'Quantum Star',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⭐', size: 13 },
      },
    ],
  },
];

save('src/data/categories/techCursors.ts', 'TECH_CURSORS', TECH_DATA);

// 8. SPECIAL CURSORS (25 EXCLUSIVE HYBRID DROPS - NOT IN GALLERY)
const SPECIAL_DATA = [
  {
    id: 'sp-hyper-phoenix',
    title: 'Hyper Phoenix Golden Talon & Solar Flare',
    slug: 'hyper-phoenix-golden-talon-solar-flare',
    category: 'Special Drops',
    description: 'Mythical immortal Sun Phoenix flaming talon wielding blazing solar burst.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['phoenix', 'mythic', 'legendary', 'fire', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'MythicArtisan',
    isFeatured: true,
    isAnimated: true,
    animationType: 'pulse',
    downloadsCount: 104500,
    likesCount: 49200,
    layers: [
      {
        id: 'ph-talon',
        name: 'Phoenix Talon',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🦅', size: 26 },
        glow: { enabled: true, color: '#f97316', blur: 6 },
      },
      {
        id: 'ph-fire',
        name: 'Solar Flare',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔥', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'ph-ptr-sun',
        name: 'Solar Corona',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '☀️', size: 24 },
        glow: { enabled: true, color: '#ea580c', blur: 8 },
      },
      {
        id: 'ph-ptr-spark',
        name: 'Fire Feather',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🪶', size: 13 },
      },
    ],
  },
  {
    id: 'sp-chronos-time',
    title: 'Chronos Time Hourglass & Infinite Relic',
    slug: 'chronos-time-hourglass-infinite-relic',
    category: 'Special Drops',
    description: 'Master of Chronos hourglass reversing sand grains with eternity infinity symbol.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['chronos', 'time', 'hourglass', 'magic', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'TimeKeeper',
    isFeatured: true,
    isAnimated: true,
    animationType: 'spin',
    downloadsCount: 98700,
    likesCount: 46100,
    layers: [
      {
        id: 'ch-glass',
        name: 'Time Hourglass',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⏳', size: 26 },
        glow: { enabled: true, color: '#f59e0b', blur: 6 },
      },
      {
        id: 'ch-sand',
        name: 'Golden Sand',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'ch-ptr-clock',
        name: 'Pocket Watch',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🕰️', size: 24 },
        glow: { enabled: true, color: '#d97706', blur: 8 },
      },
      {
        id: 'ch-ptr-gear',
        name: 'Chrono Gear',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⚙️', size: 13 },
      },
    ],
  },
  {
    id: 'sp-valkyrie-lance',
    title: 'Valkyrie Heavenly Lance & Silver Wings',
    slug: 'valkyrie-heavenly-lance-silver-wings',
    category: 'Special Drops',
    description: 'Norse Valkyrie divine golden spear with iridescent feathered silver wings.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 4 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['valkyrie', 'spear', 'wings', 'norse', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'AsgardForge',
    isFeatured: true,
    isAnimated: true,
    animationType: 'sparkle',
    downloadsCount: 89400,
    likesCount: 41200,
    layers: [
      {
        id: 'vk-lance',
        name: 'Divine Lance',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: -45,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔱', size: 26 },
        glow: { enabled: true, color: '#38bdf8', blur: 6 },
      },
      {
        id: 'vk-feather',
        name: 'Silver Feather',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🪶', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'vk-ptr-shield',
        name: 'Heavenly Shield',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🛡️', size: 24 },
        glow: { enabled: true, color: '#0284c7', blur: 8 },
      },
      {
        id: 'vk-ptr-star',
        name: 'Divine Halo',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⭐', size: 13 },
      },
    ],
  },
  {
    id: 'sp-abyssal-kraken',
    title: 'Abyssal Kraken Tentacle & Sunken Treasure',
    slug: 'abyssal-kraken-tentacle-sunken-treasure',
    category: 'Special Drops',
    description: 'Deep ocean mythical sea monster kraken tentacle with glowing cursed gold chest.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['kraken', 'ocean', 'tentacle', 'treasure', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'DeepOceanLord',
    isFeatured: true,
    isAnimated: true,
    animationType: 'wiggle',
    downloadsCount: 76500,
    likesCount: 34900,
    layers: [
      {
        id: 'kr-tent',
        name: 'Kraken Tentacle',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🐙', size: 26 },
        glow: { enabled: true, color: '#0d9488', blur: 6 },
      },
      {
        id: 'kr-bubble',
        name: 'Abyssal Bubble',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🫧', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'kr-ptr-chest',
        name: 'Gold Chest',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🪙', size: 24 },
        glow: { enabled: true, color: '#14b8a6', blur: 8 },
      },
      {
        id: 'kr-ptr-anchor',
        name: 'Sunken Anchor',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⚓', size: 13 },
      },
    ],
  },
  {
    id: 'sp-celestial-dragon',
    title: 'Celestial Dragon Pearl & Jade Flame',
    slug: 'celestial-dragon-pearl-jade-flame',
    category: 'Special Drops',
    description: 'Eastern sovereign sky dragon holding glowing emerald jade pearl with mystical clouds.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['dragon', 'jade', 'celestial', 'pearl', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'EasternDynasty',
    isFeatured: true,
    isAnimated: true,
    animationType: 'sparkle',
    downloadsCount: 112000,
    likesCount: 52400,
    layers: [
      {
        id: 'cd-dragon',
        name: 'Dragon Head',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🐉', size: 26 },
        glow: { enabled: true, color: '#10b981', blur: 6 },
      },
      {
        id: 'cd-pearl',
        name: 'Jade Pearl',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🟢', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'cd-ptr-cloud',
        name: 'Jade Cloud',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '☁️', size: 24 },
        glow: { enabled: true, color: '#059669', blur: 8 },
      },
      {
        id: 'cd-ptr-fire',
        name: 'Jade Flame',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔥', size: 13 },
      },
    ],
  },
  {
    id: 'sp-astral-unicorn',
    title: 'Astral Constellation Unicorn & Star Dust',
    slug: 'astral-constellation-unicorn-star-dust',
    category: 'Special Drops',
    description: 'Deep cosmic starlight unicorn illuminated by nebula clusters and meteor tail.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['unicorn', 'astral', 'constellation', 'stars', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'AstralDream',
    isFeatured: true,
    isAnimated: true,
    animationType: 'rainbow',
    downloadsCount: 94100,
    likesCount: 43800,
    layers: [
      {
        id: 'au-head',
        name: 'Astral Unicorn',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🦄', size: 26 },
        glow: { enabled: true, color: '#ec4899', blur: 6 },
      },
      {
        id: 'au-star',
        name: 'Nebula Star',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'au-ptr-comet',
        name: 'Meteor Comet',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '☄️', size: 24 },
        glow: { enabled: true, color: '#f43f5e', blur: 8 },
      },
      {
        id: 'au-ptr-spark',
        name: 'Stardust',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⭐', size: 13 },
      },
    ],
  },
  {
    id: 'sp-frost-excalibur',
    title: 'Glacial Excalibur & Cryo Crystal',
    slug: 'glacial-excalibur-cryo-crystal',
    category: 'Special Drops',
    description: 'Sub-zero enchanted broadsword forged from eternal mountain ice with frost shards.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 4 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['excalibur', 'ice', 'frost', 'sword', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'FrostPeakForge',
    isFeatured: true,
    isAnimated: true,
    animationType: 'sparkle',
    downloadsCount: 85200,
    likesCount: 38900,
    layers: [
      {
        id: 'fx-blade',
        name: 'Frost Blade',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: -45,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🗡️', size: 26 },
        glow: { enabled: true, color: '#38bdf8', blur: 6 },
      },
      {
        id: 'fx-snow',
        name: 'Ice Crystal',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '❄️', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'fx-ptr-cube',
        name: 'Glacier Core',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🧊', size: 24 },
        glow: { enabled: true, color: '#0284c7', blur: 8 },
      },
      {
        id: 'fx-ptr-spark',
        name: 'Frost Shimmer',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 13 },
      },
    ],
  },
  {
    id: 'sp-shadow-shuriken',
    title: 'Shadow Assassin Shuriken & Smoke Seal',
    slug: 'shadow-assassin-shuriken-smoke-seal',
    category: 'Special Drops',
    description: 'Black obsidian four-bladed throwing star vanishing into purple shadow mist.',
    cursorType: 'normal',
    hotspot: { x: 12, y: 12 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['ninja', 'shuriken', 'shadow', 'assassin', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'ShadowClan',
    isFeatured: true,
    isAnimated: true,
    animationType: 'spin',
    downloadsCount: 81700,
    likesCount: 37200,
    layers: [
      {
        id: 'ss-star',
        name: 'Black Shuriken',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✴️', size: 26 },
        glow: { enabled: true, color: '#a855f7', blur: 6 },
      },
      {
        id: 'ss-mist',
        name: 'Shadow Mist',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💨', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'ss-ptr-dagger',
        name: 'Kunai Dagger',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🗡️', size: 24 },
        glow: { enabled: true, color: '#9333ea', blur: 8 },
      },
      {
        id: 'ss-ptr-skull',
        name: 'Poison Sigil',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💀', size: 13 },
      },
    ],
  },
  {
    id: 'sp-cyber-samurai',
    title: 'Cyber Samurai Oni Mask & Plasma Scythe',
    slug: 'cyber-samurai-oni-mask-plasma-scythe',
    category: 'Special Drops',
    description: 'Holographic demon horned Oni war mask with energized violet energy scythe.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['oni', 'samurai', 'cyber', 'scythe', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'OniTech',
    isFeatured: true,
    isAnimated: true,
    animationType: 'pulse',
    downloadsCount: 108400,
    likesCount: 51200,
    layers: [
      {
        id: 'cs-mask',
        name: 'Oni Mask',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '👹', size: 26 },
        glow: { enabled: true, color: '#ef4444', blur: 6 },
      },
      {
        id: 'cs-horn',
        name: 'Plasma Spark',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⚡', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'cs-ptr-scythe',
        name: 'Plasma Scythe',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⛏️', size: 24 },
        glow: { enabled: true, color: '#dc2626', blur: 8 },
      },
      {
        id: 'cs-ptr-flame',
        name: 'Blood Fire',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔥', size: 13 },
      },
    ],
  },
  {
    id: 'sp-retro-gameboy',
    title: 'Classic 8-Bit GameBoy & Cartridge Core',
    slug: 'classic-8-bit-gameboy-cartridge-core',
    category: 'Special Drops',
    description: 'Nostalgic handheld DMG Game Console with green LCD screen and gold contact cartridge.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['gameboy', 'retro', '8bit', 'nintendo', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'RetroVault',
    isFeatured: true,
    isAnimated: true,
    animationType: 'wiggle',
    downloadsCount: 92300,
    likesCount: 42700,
    layers: [
      {
        id: 'gb-console',
        name: 'GameBoy Console',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🕹️', size: 26 },
        glow: { enabled: true, color: '#84cc16', blur: 6 },
      },
      {
        id: 'gb-screen',
        name: 'Dot Matrix Screen',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🟢', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'gb-ptr-cart',
        name: 'Game Cartridge',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💾', size: 24 },
        glow: { enabled: true, color: '#65a30d', blur: 8 },
      },
      {
        id: 'gb-ptr-battery',
        name: 'Full Battery',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔋', size: 13 },
      },
    ],
  },
  {
    id: 'sp-necro-reaper',
    title: 'Grim Reaper Scythe & Soul Lantern',
    slug: 'grim-reaper-scythe-soul-lantern',
    category: 'Special Drops',
    description: 'Ancient shadowy Reaper scythe reaping cyan spiritual wisps inside a soul cage lantern.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 4 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['reaper', 'death', 'scythe', 'lantern', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'UnderworldKing',
    isFeatured: true,
    isAnimated: true,
    animationType: 'sparkle',
    downloadsCount: 97800,
    likesCount: 45600,
    layers: [
      {
        id: 'nr-scythe',
        name: 'Death Scythe',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: -45,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🗡️', size: 26 },
        glow: { enabled: true, color: '#06b6d4', blur: 6 },
      },
      {
        id: 'nr-soul',
        name: 'Cyan Soul',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '👻', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'nr-ptr-lantern',
        name: 'Soul Lantern',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🏮', size: 24 },
        glow: { enabled: true, color: '#0891b2', blur: 8 },
      },
      {
        id: 'nr-ptr-skull',
        name: 'Reaper Skull',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💀', size: 13 },
      },
    ],
  },
  {
    id: 'sp-crystal-pegasus',
    title: 'Prismatic Crystal Pegasus & Diamond Comet',
    slug: 'prismatic-crystal-pegasus-diamond-comet',
    category: 'Special Drops',
    description: 'Glittering diamond facet winged Pegasus taking flight across crystal heavens.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['pegasus', 'crystal', 'diamond', 'prismatic', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'PrismPalace',
    isFeatured: true,
    isAnimated: true,
    animationType: 'sparkle',
    downloadsCount: 86400,
    likesCount: 39800,
    layers: [
      {
        id: 'cp-horse',
        name: 'Pegasus Head',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🦄', size: 26 },
        glow: { enabled: true, color: '#a78bfa', blur: 6 },
      },
      {
        id: 'cp-gem',
        name: 'Diamond Facet',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💎', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'cp-ptr-star',
        name: 'Prism Star',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⭐', size: 24 },
        glow: { enabled: true, color: '#8b5cf6', blur: 8 },
      },
      {
        id: 'cp-ptr-feather',
        name: 'Crystal Feather',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🪶', size: 13 },
      },
    ],
  },
  {
    id: 'sp-inferno-cerberus',
    title: 'Inferno Cerberus Claw & Hellfire Collar',
    slug: 'inferno-cerberus-claw-hellfire-collar',
    category: 'Special Drops',
    description: 'Three-headed underworld guardian beast claw engulfed in volcanic magma eruption.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['cerberus', 'inferno', 'hellfire', 'magma', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'VolcanoForge',
    isFeatured: true,
    isAnimated: true,
    animationType: 'pulse',
    downloadsCount: 78900,
    likesCount: 36200,
    layers: [
      {
        id: 'ic-paw',
        name: 'Cerberus Paw',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🐺', size: 26 },
        glow: { enabled: true, color: '#ea580c', blur: 6 },
      },
      {
        id: 'ic-fire',
        name: 'Magma Spark',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔥', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'ic-ptr-chain',
        name: 'Spike Collar',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⛓️', size: 24 },
        glow: { enabled: true, color: '#c2410c', blur: 8 },
      },
      {
        id: 'ic-ptr-lava',
        name: 'Lava Rock',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🪨', size: 13 },
      },
    ],
  },
  {
    id: 'sp-aurora-borealis',
    title: 'Aurora Borealis Polar Compass & Star Needle',
    slug: 'aurora-borealis-polar-compass-star-needle',
    category: 'Special Drops',
    description: 'Northern lights magnetic brass nautical compass with glowing emerald green needle.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['aurora', 'compass', 'northernlights', 'polar', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'ArcticExplorer',
    isFeatured: true,
    isAnimated: true,
    animationType: 'rainbow',
    downloadsCount: 87300,
    likesCount: 40100,
    layers: [
      {
        id: 'ab-comp',
        name: 'Brass Compass',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🧭', size: 26 },
        glow: { enabled: true, color: '#10b981', blur: 6 },
      },
      {
        id: 'ab-wave',
        name: 'Aurora Shimmer',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'ab-ptr-globe',
        name: 'Polar Globe',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🌐', size: 24 },
        glow: { enabled: true, color: '#059669', blur: 8 },
      },
      {
        id: 'ab-ptr-star',
        name: 'North Star',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⭐', size: 13 },
      },
    ],
  },
  {
    id: 'sp-void-relic',
    title: 'Void Relic Obelisk & Purple Event Horizon',
    slug: 'void-relic-obelisk-event-horizon',
    category: 'Special Drops',
    description: 'Extraterrestrial floating dark purple obelisk with cosmic grav-well rings.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 4 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['void', 'obelisk', 'alien', 'gravity', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'VoidArchitect',
    isFeatured: true,
    isAnimated: true,
    animationType: 'pulse',
    downloadsCount: 83400,
    likesCount: 38200,
    layers: [
      {
        id: 'vr-obelisk',
        name: 'Void Pillar',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🗿', size: 26 },
        glow: { enabled: true, color: '#7c3aed', blur: 6 },
      },
      {
        id: 'vr-orbit',
        name: 'Event Ring',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🟣', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'vr-ptr-crystal',
        name: 'Dark Crystal',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔮', size: 24 },
        glow: { enabled: true, color: '#6d28d9', blur: 8 },
      },
      {
        id: 'vr-ptr-spark',
        name: 'Singularity Particle',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 13 },
      },
    ],
  },
  {
    id: 'sp-glitch-arcade',
    title: 'Glitch Pixel Arcade Joystick & CRT Static',
    slug: 'glitch-pixel-arcade-joystick-crt-static',
    category: 'Special Drops',
    description: 'RGB channel split distorted retro red ball joystick with cyan glitch scanline.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['glitch', 'arcade', 'joystick', 'pixel', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'GlitchMaster',
    isFeatured: true,
    isAnimated: true,
    animationType: 'wiggle',
    downloadsCount: 91400,
    likesCount: 41900,
    layers: [
      {
        id: 'ga-stick',
        name: 'Arcade Stick',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🕹️', size: 26 },
        glow: { enabled: true, color: '#ec4899', blur: 6 },
      },
      {
        id: 'ga-noise',
        name: 'Glitch Zap',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⚡', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'ga-ptr-btn',
        name: 'Arcade Button',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔴', size: 24 },
        glow: { enabled: true, color: '#06b6d4', blur: 8 },
      },
      {
        id: 'ga-ptr-star',
        name: 'Pixel Star',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⭐', size: 13 },
      },
    ],
  },
  {
    id: 'sp-thunder-zeus',
    title: 'Thunder God Zeus Lightning & Olympus Spark',
    slug: 'thunder-god-zeus-lightning-olympus',
    category: 'Special Drops',
    description: 'Blinding electric Greek master bolt crackling with ozone and celestial fury.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['zeus', 'lightning', 'thunder', 'greek', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'OlympusHalls',
    isFeatured: true,
    isAnimated: true,
    animationType: 'sparkle',
    downloadsCount: 102300,
    likesCount: 47800,
    layers: [
      {
        id: 'tz-bolt',
        name: 'Master Bolt',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: -25,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⚡', size: 26 },
        glow: { enabled: true, color: '#eab308', blur: 6 },
      },
      {
        id: 'tz-cloud',
        name: 'Storm Cloud',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🌩️', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'tz-ptr-eagle',
        name: 'Olympian Eagle',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🦅', size: 24 },
        glow: { enabled: true, color: '#ca8a04', blur: 8 },
      },
      {
        id: 'tz-ptr-spark',
        name: 'Thunder Zap',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 13 },
      },
    ],
  },
  {
    id: 'sp-toxic-slime',
    title: 'Neon Radioactive Slime & Bio Toxic Barrel',
    slug: 'neon-radioactive-slime-bio-toxic-barrel',
    category: 'Special Drops',
    description: 'Bouncing fluorescent chemical green slime creature with radioactive isotope badge.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['slime', 'toxic', 'biohazard', 'neon', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'HazardZone',
    isFeatured: true,
    isAnimated: true,
    animationType: 'wiggle',
    downloadsCount: 75800,
    likesCount: 33400,
    layers: [
      {
        id: 'ts-slime',
        name: 'Slime Blob',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🟢', size: 26 },
        glow: { enabled: true, color: '#84cc16', blur: 6 },
      },
      {
        id: 'ts-rad',
        name: 'Radioactive Spark',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '☣️', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'ts-ptr-barrel',
        name: 'Toxic Barrel',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🛢️', size: 24 },
        glow: { enabled: true, color: '#65a30d', blur: 8 },
      },
      {
        id: 'ts-ptr-drop',
        name: 'Acid Splat',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💧', size: 13 },
      },
    ],
  },
  {
    id: 'sp-spirit-fox',
    title: 'Kitsune Nine-Tails Spirit Fox & Sacred Shinto Bell',
    slug: 'kitsune-spirit-fox-shinto-bell',
    category: 'Special Drops',
    description: 'Golden spirit fox kitsune with blue ghostly will-o-wisp orbs and Shinto shrine bell.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['kitsune', 'fox', 'spirit', 'shinto', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'KyotoSpirits',
    isFeatured: true,
    isAnimated: true,
    animationType: 'sparkle',
    downloadsCount: 96500,
    likesCount: 44300,
    layers: [
      {
        id: 'kf-fox',
        name: 'Kitsune Head',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🦊', size: 26 },
        glow: { enabled: true, color: '#f97316', blur: 6 },
      },
      {
        id: 'kf-wisp',
        name: 'Foxfire Flame',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔥', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'kf-ptr-bell',
        name: 'Sacred Bell',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔔', size: 24 },
        glow: { enabled: true, color: '#ea580c', blur: 8 },
      },
      {
        id: 'kf-ptr-spark',
        name: 'Spirit Charm',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 13 },
      },
    ],
  },
  {
    id: 'sp-plasma-shield',
    title: 'Aegis Forcefield Plasma Barrier & Quantum Hex',
    slug: 'aegis-forcefield-plasma-barrier-quantum-hex',
    category: 'Special Drops',
    description: 'Hexagonal honeycomb energy barrier deflecting incoming laser artillery fire.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['shield', 'forcefield', 'plasma', 'hex', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'DefenseGrid',
    isFeatured: true,
    isAnimated: true,
    animationType: 'pulse',
    downloadsCount: 71200,
    likesCount: 31900,
    layers: [
      {
        id: 'ps-shield',
        name: 'Aegis Barrier',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🛡️', size: 26 },
        glow: { enabled: true, color: '#06b6d4', blur: 6 },
      },
      {
        id: 'ps-spark',
        name: 'Deflection Spark',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⚡', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'ps-ptr-core',
        name: 'Reactor Core',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💠', size: 24 },
        glow: { enabled: true, color: '#0891b2', blur: 8 },
      },
      {
        id: 'ps-ptr-hex',
        name: 'Hex Grid',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 13 },
      },
    ],
  },
  {
    id: 'sp-ruby-dagger',
    title: 'Blood Ruby Ceremonial Dagger & Crimson Gem',
    slug: 'blood-ruby-ceremonial-dagger-crimson-gem',
    category: 'Special Drops',
    description: 'Gilded dragon-hilt stiletto dagger encrusted with fiery glowing pigeon-blood ruby.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 4 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['ruby', 'dagger', 'gem', 'crimson', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'ImperialVault',
    isFeatured: true,
    isAnimated: true,
    animationType: 'sparkle',
    downloadsCount: 88900,
    likesCount: 40700,
    layers: [
      {
        id: 'rd-blade',
        name: 'Ruby Blade',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: -45,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🗡️', size: 26 },
        glow: { enabled: true, color: '#ef4444', blur: 6 },
      },
      {
        id: 'rd-ruby',
        name: 'Red Ruby Gem',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💎', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'rd-ptr-heart',
        name: 'Crimson Heart',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '❤️', size: 24 },
        glow: { enabled: true, color: '#dc2626', blur: 8 },
      },
      {
        id: 'rd-ptr-spark',
        name: 'Ruby Glint',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 13 },
      },
    ],
  },
  {
    id: 'sp-space-shuttle',
    title: 'Orbital Discovery Shuttle & Lunar Crater',
    slug: 'orbital-discovery-shuttle-lunar-crater',
    category: 'Special Drops',
    description: 'NASA space shuttle blazing solid rocket booster flames climbing through ionosphere.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['nasa', 'shuttle', 'space', 'rocket', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'CapeCanaveral',
    isFeatured: true,
    isAnimated: true,
    animationType: 'sparkle',
    downloadsCount: 79100,
    likesCount: 35600,
    layers: [
      {
        id: 'os-shuttle',
        name: 'Space Shuttle',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: -30,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🚀', size: 26 },
        glow: { enabled: true, color: '#f97316', blur: 6 },
      },
      {
        id: 'os-smoke',
        name: 'Booster Flame',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔥', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'os-ptr-moon',
        name: 'Full Moon',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🌕', size: 24 },
        glow: { enabled: true, color: '#eab308', blur: 8 },
      },
      {
        id: 'os-ptr-star',
        name: 'Space Star',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⭐', size: 13 },
      },
    ],
  },
  {
    id: 'sp-alchemist-flask',
    title: 'Philosopher Gold Flask & Bubbling Elixir',
    slug: 'philosopher-gold-flask-bubbling-elixir',
    category: 'Special Drops',
    description: 'Round-bottom occult glass alchemy flask transmuting base metal into pure liquid gold.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['alchemy', 'flask', 'potion', 'gold', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'HermeticArt',
    isFeatured: true,
    isAnimated: true,
    animationType: 'wiggle',
    downloadsCount: 84700,
    likesCount: 38800,
    layers: [
      {
        id: 'af-flask',
        name: 'Alchemy Flask',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🧪', size: 26 },
        glow: { enabled: true, color: '#eab308', blur: 6 },
      },
      {
        id: 'af-bubble',
        name: 'Golden Bubble',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🫧', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'af-ptr-stone',
        name: 'Philosopher Stone',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💎', size: 24 },
        glow: { enabled: true, color: '#f59e0b', blur: 8 },
      },
      {
        id: 'af-ptr-spark',
        name: 'Gold Dust',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 13 },
      },
    ],
  },
  {
    id: 'sp-neon-synth-car',
    title: 'Cyberpunk DeLorean & Neon Highway',
    slug: 'cyberpunk-delorean-neon-highway',
    category: 'Special Drops',
    description: 'Hovering gullwing stainless steel retro supercar blazing twin tire fire tracks.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['delorean', 'car', 'synthwave', 'outrun', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'TimeTraveler85',
    isFeatured: true,
    isAnimated: true,
    animationType: 'sparkle',
    downloadsCount: 105800,
    likesCount: 49700,
    layers: [
      {
        id: 'nc-car',
        name: 'DeLorean Car',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🏎️', size: 26 },
        glow: { enabled: true, color: '#06b6d4', blur: 6 },
      },
      {
        id: 'nc-fire',
        name: 'Twin Fire Tracks',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔥', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'nc-ptr-speed',
        name: '88 MPH Speedometer',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⚡', size: 24 },
        glow: { enabled: true, color: '#38bdf8', blur: 8 },
      },
      {
        id: 'nc-ptr-star',
        name: 'Warp Spark',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 13 },
      },
    ],
  },
  {
    id: 'sp-infinity-crown',
    title: 'Infinity Sovereign Crown & Celestial Scepter',
    slug: 'infinity-sovereign-crown-celestial-scepter',
    category: 'Special Drops',
    description: 'The supreme royal crown studded with 6 elemental infinity gemstones.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['infinity', 'crown', 'sovereign', 'gems', 'special'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'EmperorCrown',
    isFeatured: true,
    isAnimated: true,
    animationType: 'rainbow',
    downloadsCount: 118900,
    likesCount: 56400,
    layers: [
      {
        id: 'ic-crown',
        name: 'Infinity Crown',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '👑', size: 26 },
        glow: { enabled: true, color: '#fbbf24', blur: 6 },
      },
      {
        id: 'ic-gem',
        name: 'Omni Gem',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💎', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'ic-ptr-scepter',
        name: 'Royal Scepter',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🪄', size: 24 },
        glow: { enabled: true, color: '#f59e0b', blur: 8 },
      },
      {
        id: 'ic-ptr-spark',
        name: 'Cosmic Glory',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 13 },
      },
    ],
  },
];

saveSpecial('src/data/specialCursors.ts', 'SPECIAL_CURSORS', SPECIAL_DATA);
