import fs from 'fs';

// Helper to write file
function writePresetFile(path, content) {
  fs.writeFileSync(path, content, 'utf8');
  console.log(`Wrote ${path}`);
}

// 1. GAME CURSORS
const GAME_CURSORS = `import { CursorProject } from '../../types/cursor';

export const GAME_CURSORS: CursorProject[] = [
  {
    id: 'game-minecraft-diamond',
    title: 'Minecraft Diamond Sword & Red Heart',
    slug: 'minecraft-diamond-sword-red-heart',
    category: 'Games',
    description: 'Iconic glowing blue Minecraft Diamond Sword with Sharpness V glint and health heart.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 4 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['minecraft', 'sword', 'diamond', 'gaming', 'heart'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
    author: 'SweezyCraft',
    isFeatured: true,
    isAnimated: true,
    animationType: 'sparkle',
    downloadsCount: 78500,
    likesCount: 29400,
    layers: [
      {
        id: 'mc-sword',
        name: 'Diamond Sword',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: -45,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🗡️', size: 26 },
        shadow: { enabled: true, color: 'rgba(6, 182, 212, 0.4)', blur: 4, offsetX: 0, offsetY: 0 },
      },
      {
        id: 'mc-gem',
        name: 'Diamond Gem',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 16,
        y: 12,
        width: 14,
        height: 14,
        rotation: 10,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💎', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'mc-ptr-heart',
        name: 'Health Heart',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 1,
        y: 1,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '❤️', size: 24 },
        glow: { enabled: true, color: '#ef4444', blur: 8 },
      },
      {
        id: 'mc-ptr-exp',
        name: 'Exp Orb',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 14,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🟢', size: 13 },
      },
    ],
  },
  {
    id: 'game-pikachu-thunder',
    title: 'Pikachu Thunderbolt & Red Pokeball',
    slug: 'pikachu-thunderbolt-red-pokeball',
    category: 'Games',
    description: 'Electric Pokemon Pikachu holding lightning volt with standard Poke Ball pointer.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['pokemon', 'pikachu', 'lightning', 'nintendo', 'gaming'],
    createdAt: '2026-08-19T10:00:00.000Z',
    updatedAt: '2026-08-19T10:00:00.000Z',
    author: 'PikaFan',
    isFeatured: true,
    isAnimated: true,
    animationType: 'pulse',
    downloadsCount: 65200,
    likesCount: 24100,
    layers: [
      {
        id: 'pk-volt',
        name: 'Thunderbolt',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: -20,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⚡', size: 26 },
        glow: { enabled: true, color: '#eab308', blur: 6 },
      },
      {
        id: 'pk-spark',
        name: 'Sparkle Spark',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 13 },
      },
    ],
    pointerLayers: [
      {
        id: 'pk-ptr-ball',
        name: 'Pokeball Disc',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔴', size: 24 },
      },
      {
        id: 'pk-ptr-star',
        name: 'Catch Star',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⭐', size: 13 },
      },
    ],
  },
  {
    id: 'game-amongus-impostor',
    title: 'Among Us Red Impostor & Mini Ghost',
    slug: 'among-us-red-impostor-ghost',
    category: 'Games',
    description: 'Suspicious Red Crewmate Impostor with shining visor and floating cyan mini ghost.',
    cursorType: 'normal',
    hotspot: { x: 6, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['amongus', 'impostor', 'sus', 'space', 'gaming'],
    createdAt: '2026-08-18T10:00:00.000Z',
    updatedAt: '2026-08-18T10:00:00.000Z',
    author: 'InnerslothVibe',
    isFeatured: true,
    isAnimated: true,
    animationType: 'wiggle',
    downloadsCount: 54300,
    likesCount: 19800,
    layers: [
      {
        id: 'au-knife',
        name: 'Impostor Knife',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: -45,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔪', size: 25 },
        glow: { enabled: true, color: '#ef4444', blur: 6 },
      },
      {
        id: 'au-alarm',
        name: 'Emergency Siren',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 15,
        y: 13,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🚨', size: 13 },
      },
    ],
    pointerLayers: [
      {
        id: 'au-ptr-ghost',
        name: 'Cyan Ghost',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '👻', size: 24 },
        glow: { enabled: true, color: '#06b6d4', blur: 8 },
      },
      {
        id: 'au-ptr-spark',
        name: 'Space Dust',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 12 },
      },
    ],
  },
  {
    id: 'game-mario-fireflower',
    title: 'Super Mario Fire Flower & 1-Up Mushroom',
    slug: 'mario-fire-flower-1-up-mushroom',
    category: 'Games',
    description: 'Classic glowing Super Mario Fire Flower powerup and lucky green 1-Up life mushroom.',
    cursorType: 'normal',
    hotspot: { x: 6, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['mario', 'nintendo', 'fireflower', 'mushroom', 'retro'],
    createdAt: '2026-08-17T10:00:00.000Z',
    updatedAt: '2026-08-17T10:00:00.000Z',
    author: 'NintendoFan88',
    isFeatured: true,
    isAnimated: true,
    animationType: 'bounce',
    downloadsCount: 61800,
    likesCount: 22700,
    layers: [
      {
        id: 'mr-flower',
        name: 'Fire Flower',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔥', size: 26 },
        glow: { enabled: true, color: '#f97316', blur: 6 },
      },
      {
        id: 'mr-coin',
        name: 'Gold Coin',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 15,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🪙', size: 13 },
      },
    ],
    pointerLayers: [
      {
        id: 'mr-ptr-shroom',
        name: '1-Up Mushroom',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🍄', size: 24 },
        glow: { enabled: true, color: '#22c55e', blur: 8 },
      },
      {
        id: 'mr-ptr-star',
        name: 'Star Sparkle',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⭐', size: 13 },
      },
    ],
  },
  {
    id: 'game-roblox-bloxiade',
    title: 'Roblox Bloxiade Soda & Gold Coin',
    slug: 'roblox-bloxiade-soda-gold-coin',
    category: 'Games',
    description: 'Refreshing Bloxiade energy drink with sparkling gold Robux currency coin pointer.',
    cursorType: 'normal',
    hotspot: { x: 6, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['roblox', 'bloxiade', 'robux', 'bloxfruits', 'arsenal'],
    createdAt: '2026-08-16T10:00:00.000Z',
    updatedAt: '2026-08-16T10:00:00.000Z',
    author: 'BloxMaster',
    isFeatured: true,
    isAnimated: true,
    animationType: 'sparkle',
    downloadsCount: 89200,
    likesCount: 38700,
    layers: [
      {
        id: 'rb-drink',
        name: 'Bloxiade Cup',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: -15,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🥤', size: 26 },
        glow: { enabled: true, color: '#ec4899', blur: 6 },
      },
      {
        id: 'rb-sparkle',
        name: 'Sparkle Energy',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'rb-ptr-coin',
        name: 'Gold Robux Coin',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🪙', size: 24 },
        glow: { enabled: true, color: '#eab308', blur: 8 },
      },
      {
        id: 'rb-ptr-gem',
        name: 'Diamond Sparkle',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💎', size: 13 },
      },
    ],
  },
  {
    id: 'game-valorant-radiant',
    title: 'Valorant Radiant Dagger & Defuser',
    slug: 'valorant-radiant-dagger-defuser',
    category: 'Games',
    description: 'Sleek tactical Valorant melee blade in vibrant teal with glowing Spike gadget.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 4 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['valorant', 'riot', 'tactical', 'dagger', 'radiant'],
    createdAt: '2026-08-15T10:00:00.000Z',
    updatedAt: '2026-08-15T10:00:00.000Z',
    author: 'ViperMain',
    isFeatured: true,
    isAnimated: true,
    animationType: 'pulse',
    downloadsCount: 52100,
    likesCount: 19400,
    layers: [
      {
        id: 'val-knife',
        name: 'Tactical Knife',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: -45,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🗡️', size: 26 },
        glow: { enabled: true, color: '#14b8a6', blur: 6 },
      },
      {
        id: 'val-target',
        name: 'Bullseye Crosshair',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 15,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🎯', size: 13 },
      },
    ],
    pointerLayers: [
      {
        id: 'val-ptr-bomb',
        name: 'Spike Core',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💣', size: 24 },
        glow: { enabled: true, color: '#ef4444', blur: 8 },
      },
      {
        id: 'val-ptr-fire',
        name: 'Flame Blast',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔥', size: 13 },
      },
    ],
  },
  {
    id: 'game-genshin-primogem',
    title: 'Genshin Primogem & Intertwined Fate',
    slug: 'genshin-primogem-intertwined-fate',
    category: 'Games',
    description: 'Sparkling four-pointed Primogem currency with rainbow 5-star shooting comet star.',
    cursorType: 'normal',
    hotspot: { x: 6, y: 4 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['genshin', 'primogem', 'anime', 'gacha', 'hoyoverse'],
    createdAt: '2026-08-14T10:00:00.000Z',
    updatedAt: '2026-08-14T10:00:00.000Z',
    author: 'PaimonBest',
    isFeatured: true,
    isAnimated: true,
    animationType: 'rainbow',
    downloadsCount: 71900,
    likesCount: 31200,
    layers: [
      {
        id: 'gi-star',
        name: 'Primogem Star',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '💠', size: 26 },
        glow: { enabled: true, color: '#818cf8', blur: 6 },
      },
      {
        id: 'gi-sparkle',
        name: 'Glimmer',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 14 },
      },
    ],
    pointerLayers: [
      {
        id: 'gi-ptr-fate',
        name: 'Intertwined Fate',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔮', size: 24 },
        glow: { enabled: true, color: '#ec4899', blur: 8 },
      },
      {
        id: 'gi-ptr-comet',
        name: 'Golden Wish',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⭐', size: 13 },
      },
    ],
  },
  {
    id: 'game-zelda-mastersword',
    title: 'Zelda Master Sword & Golden Triforce',
    slug: 'zelda-master-sword-triforce',
    category: 'Games',
    description: 'The legendary Blade of Evil Bane with shining sacred Golden Triforce relic.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 4 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['zelda', 'link', 'mastersword', 'triforce', 'hyrule'],
    createdAt: '2026-08-13T10:00:00.000Z',
    updatedAt: '2026-08-13T10:00:00.000Z',
    author: 'HeroOfTime',
    isFeatured: true,
    isAnimated: true,
    animationType: 'sparkle',
    downloadsCount: 68400,
    likesCount: 26500,
    layers: [
      {
        id: 'zd-sword',
        name: 'Master Sword',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: -45,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🗡️', size: 26 },
        glow: { enabled: true, color: '#38bdf8', blur: 6 },
      },
      {
        id: 'zd-shield',
        name: 'Hylian Shield',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 15,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🛡️', size: 13 },
      },
    ],
    pointerLayers: [
      {
        id: 'zd-ptr-tri',
        name: 'Golden Triforce',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🔺', size: 24 },
        glow: { enabled: true, color: '#fbbf24', blur: 8 },
      },
      {
        id: 'zd-ptr-spark',
        name: 'Goddess Light',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '✨', size: 13 },
      },
    ],
  },
  {
    id: 'game-pacman-arcade',
    title: 'Pac-Man Arcade & Retro Cherry',
    slug: 'pacman-arcade-retro-cherry',
    category: 'Games',
    description: 'Chomping retro yellow Pac-Man with pixel power pellet cherries and blue ghost.',
    cursorType: 'normal',
    hotspot: { x: 4, y: 4 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['pacman', 'arcade', 'retro', '80s', 'pixel'],
    createdAt: '2026-08-12T10:00:00.000Z',
    updatedAt: '2026-08-12T10:00:00.000Z',
    author: 'RetroNamco',
    isFeatured: true,
    isAnimated: true,
    animationType: 'wiggle',
    downloadsCount: 47900,
    likesCount: 16800,
    layers: [
      {
        id: 'pm-pac',
        name: 'Chomping Pac-Man',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🟡', size: 25 },
        glow: { enabled: true, color: '#facc15', blur: 6 },
      },
      {
        id: 'pm-dot',
        name: 'Power Pellet',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 16,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⚪', size: 12 },
      },
    ],
    pointerLayers: [
      {
        id: 'pm-ptr-cherry',
        name: 'Pixel Cherry',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🍒', size: 24 },
        glow: { enabled: true, color: '#f43f5e', blur: 8 },
      },
      {
        id: 'pm-ptr-ghost',
        name: 'Blue Ghost',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '👻', size: 13 },
      },
    ],
  },
  {
    id: 'game-fortnite-crown',
    title: 'Fortnite Victory Crown & Loot Llama',
    slug: 'fortnite-victory-crown-loot-llama',
    category: 'Games',
    description: 'Golden Victory Royale crown with colorful pinata Loot Llama bonus pointer.',
    cursorType: 'normal',
    hotspot: { x: 6, y: 2 },
    pointerHotspot: { x: 12, y: 4 },
    tags: ['fortnite', 'crown', 'llama', 'battleroyale', 'gaming'],
    createdAt: '2026-08-11T10:00:00.000Z',
    updatedAt: '2026-08-11T10:00:00.000Z',
    author: 'VictoryKing',
    isFeatured: true,
    isAnimated: true,
    animationType: 'sparkle',
    downloadsCount: 56700,
    likesCount: 21900,
    layers: [
      {
        id: 'fn-crown',
        name: 'Victory Crown',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        width: 28,
        height: 28,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '👑', size: 26 },
        glow: { enabled: true, color: '#f59e0b', blur: 6 },
      },
      {
        id: 'fn-star',
        name: 'Victory Star',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 15,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '⭐', size: 13 },
      },
    ],
    pointerLayers: [
      {
        id: 'fn-ptr-llama',
        name: 'Loot Llama',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 2,
        y: 2,
        width: 26,
        height: 26,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '🦙', size: 24 },
        glow: { enabled: true, color: '#a855f7', blur: 8 },
      },
      {
        id: 'fn-ptr-box',
        name: 'Supply Drop',
        type: 'emoji',
        visible: true,
        locked: false,
        opacity: 1,
        x: 14,
        y: 12,
        width: 14,
        height: 14,
        rotation: 0,
        fill: '#ffffff',
        stroke: '#ffffff',
        strokeWidth: 1,
        emojiData: { char: '📦', size: 13 },
      },
    ],
  },
];
`;

writePresetFile('src/data/categories/gameCursors.ts', GAME_CURSORS);
